## Python Libraries for Data Science
- Numpy
- Pandas
- Matplotlib

#### numpy --> numerical python
- numpy is Base N-dimensional array package, is a python library and a fundamental package for scientific applications,it is used to create multidimensional arrays for the fast operations.
- ex: import numpy as np



In [1]:
# create 1D array
import numpy as np
array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [2]:
# create 2D array
import numpy as np
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
li = [1,2,3]
a = np.array(li)
print(a)


[1 2 3]


In [9]:
import numpy as np
a1 = np.array(range(1,12))
print(a1)


[ 1  2  3  4  5  6  7  8  9 10 11]


In [10]:
import numpy as np
a2 = np.arange(15)
print(a2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
import numpy as np
a3 = np.arange(10).reshape(2,5)
a3


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
# reverse the array
a3[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [13]:
import numpy as np
a4 = np.ones((3,3))
print(a4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
import numpy as np
a5 = np.zeros((3,3))
print(a5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# create 3D array
x = [[1,2,3],[10,20,30],[11,22,33]]
y = np.array(x)
#print(y)
y

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [17]:
z=y+1
z

array([[ 2,  3,  4],
       [11, 21, 31],
       [12, 23, 34]])

In [18]:
p = [1,2,3]

q = np.array(p)
print(q)

[1 2 3]


In [19]:
print(np.sqrt(q))

[1.         1.41421356 1.73205081]


In [20]:
print(np.sin(q))

[0.84147098 0.90929743 0.14112001]


In [21]:
print(np.cos(q))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [22]:
print(np.log(q))

[0.         0.69314718 1.09861229]


In [25]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(5,11).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [24]:
print(b,'\n')

[[ 5  6  7]
 [ 8  9 10]] 



In [26]:
print(a+b)

[[ 6  8 10]
 [12 14 16]]


In [27]:
print(a/b)

[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [31]:
x1 = np.arange(10000).reshape(100,100)
x1

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [32]:
x1.size

10000

In [33]:
x1.shape

(100, 100)

In [34]:
x1.itemsize

4

In [35]:
x1.data

In [36]:
x1.dtype

dtype('int32')

In [37]:
x1.ndim

2